// <auto-generated />
namespace FullstackPluralsightProjectToLearn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OverriedConventionsForGigsAndGenres2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverriedConventionsForGigsAndGenres2));
        
        string IMigrationMetadata.Id
        {
            get { return "201704271428063_OverriedConventionsForGigsAndGenres2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
